// Mock data for the application
export const mockProperties = [
  {
    id: 1,
    title: "Luxury Villa in Budhanilkantha",
    description:
      "Stunning luxury villa with panoramic mountain views. This exceptional property features modern architecture blended with traditional Nepali design elements. Spacious rooms, high ceilings, and premium finishes throughout. Perfect for families seeking tranquility while staying close to the city.",
    price: "45000000",
    location: "Budhanilkantha, Kathmandu",
    property_type: "Villa",
    status: "For Sale",
    bedrooms: 5,
    bathrooms: 4,
    area: 350,
    image_url: "/luxury-villa-nepal-mountains.jpg",
    agent_id: 1,
    agent_name: "Rajesh Kumar",
    agent_phone: "+977-9841234567",
    agent_email: "rajesh.kumar@nepalestate.com",
    agent_image: "/professional-nepali-male-real-estate-agent.jpg",
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: 2,
    title: "Modern Apartment in Lazimpat",
    description:
      "Contemporary apartment in the heart of Kathmandu's diplomatic zone. Features include modern kitchen, spacious balcony, and secure parking. Walking distance to restaurants, cafes, and shopping centers. Ideal for professionals and small families.",
    price: "18500000",
    location: "Lazimpat, Kathmandu",
    property_type: "Apartment",
    status: "For Sale",
    bedrooms: 3,
    bathrooms: 2,
    area: 145,
    image_url: "/modern-apartment-kathmandu.jpg",
    agent_id: 2,
    agent_name: "Sita Thapa",
    agent_phone: "+977-9851234568",
    agent_email: "sita.thapa@nepalestate.com",
    agent_image: "/professional-nepali-female-real-estate-agent.jpg",
    created_at: "2024-02-01T10:00:00Z",
  },
  {
    id: 3,
    title: "Lakeside House in Pokhara",
    description:
      "Beautiful lakeside property with stunning views of Phewa Lake and the Annapurna range. Perfect for those seeking a peaceful lifestyle or vacation home. Features include large garden, outdoor seating area, and direct lake access.",
    price: "28000000",
    location: "Lakeside, Pokhara",
    property_type: "House",
    status: "For Sale",
    bedrooms: 4,
    bathrooms: 3,
    area: 220,
    image_url: "/lakeside-house-pokhara-nepal.jpg",
    agent_id: 3,
    agent_name: "Bikram Gurung",
    agent_phone: "+977-9861234569",
    agent_email: "bikram.gurung@nepalestate.com",
    agent_image: "/professional-nepali-male-real-estate-agent-smiling.jpg",
    created_at: "2024-02-10T10:00:00Z",
  },
  {
    id: 4,
    title: "Commercial Space in Thamel",
    description:
      "Prime commercial property in Kathmandu's tourist hub. High foot traffic area perfect for restaurants, cafes, or retail shops. Ground floor with large display windows and ample space for business operations.",
    price: "35000000",
    location: "Thamel, Kathmandu",
    property_type: "Commercial",
    status: "For Rent",
    bedrooms: 0,
    bathrooms: 2,
    area: 180,
    image_url: "/commercial-building-in-thamel-kathmandu-nepal.jpg",
    agent_id: 1,
    agent_name: "Rajesh Kumar",
    agent_phone: "+977-9841234567",
    agent_email: "rajesh.kumar@nepalestate.com",
    agent_image: "/professional-nepali-male-real-estate-agent.jpg",
    created_at: "2024-02-15T10:00:00Z",
  },
  {
    id: 5,
    title: "Mountain View Cottage in Nagarkot",
    description:
      "Charming cottage with breathtaking Himalayan views. Perfect weekend getaway or retirement home. Features include fireplace, wooden interiors, and large terrace for enjoying sunrise views over the mountains.",
    price: "22000000",
    location: "Nagarkot, Bhaktapur",
    property_type: "House",
    status: "For Sale",
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
    image_url: "/mountain-cottage-nagarkot-nepal-himalayan-view.jpg",
    agent_id: 4,
    agent_name: "Anita Shrestha",
    agent_phone: "+977-9871234570",
    agent_email: "anita.shrestha@nepalestate.com",
    agent_image: "/professional-nepali-female-real-estate-agent-confi.jpg",
    created_at: "2024-02-20T10:00:00Z",
  },
  {
    id: 6,
    title: "Penthouse in Jhamsikhel",
    description:
      "Luxurious penthouse in trendy Jhamsikhel area. Top floor unit with 360-degree views, modern amenities, and rooftop access. Close to cafes, restaurants, and art galleries. Perfect for urban lifestyle enthusiasts.",
    price: "42000000",
    location: "Jhamsikhel, Lalitpur",
    property_type: "Apartment",
    status: "For Sale",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    image_url: "/luxury-penthouse-apartment-kathmandu-nepal-modern.jpg",
    agent_id: 2,
    agent_name: "Sita Thapa",
    agent_phone: "+977-9851234568",
    agent_email: "sita.thapa@nepalestate.com",
    agent_image: "/professional-nepali-female-real-estate-agent.jpg",
    created_at: "2024-03-01T10:00:00Z",
  },
]

export const mockAgents = [
  {
    id: 1,
    name: "Rajesh Kumar",
    email: "rajesh.kumar@nepalestate.com",
    phone: "+977-9841234567",
    bio: "With over 15 years of experience in Nepal's real estate market, Rajesh specializes in luxury properties and commercial spaces. His deep understanding of Kathmandu's property landscape and commitment to client satisfaction has made him one of the most trusted agents in the industry.",
    specialization: "Luxury Properties & Commercial",
    properties_sold: 127,
    image_url: "/professional-nepali-male-real-estate-agent.jpg",
  },
  {
    id: 2,
    name: "Sita Thapa",
    email: "sita.thapa@nepalestate.com",
    phone: "+977-9851234568",
    bio: "Sita brings a fresh perspective to real estate with her focus on modern apartments and urban living spaces. Her expertise in the Lalitpur and Kathmandu areas, combined with her excellent negotiation skills, ensures her clients get the best deals possible.",
    specialization: "Apartments & Urban Properties",
    properties_sold: 98,
    image_url: "/professional-nepali-female-real-estate-agent.jpg",
  },
  {
    id: 3,
    name: "Bikram Gurung",
    email: "bikram.gurung@nepalestate.com",
    phone: "+977-9861234569",
    bio: "Based in Pokhara, Bikram is the go-to expert for lakeside and mountain properties. His passion for Nepal's natural beauty and extensive network in the Pokhara region makes him invaluable for clients seeking vacation homes or investment properties outside Kathmandu.",
    specialization: "Lakeside & Mountain Properties",
    properties_sold: 85,
    image_url: "/professional-nepali-male-real-estate-agent-smiling.jpg",
  },
  {
    id: 4,
    name: "Anita Shrestha",
    email: "anita.shrestha@nepalestate.com",
    phone: "+977-9871234570",
    bio: "Anita's expertise lies in residential properties and helping families find their perfect home. Her patient approach and attention to detail ensure that every client finds a property that truly meets their needs and budget.",
    specialization: "Residential & Family Homes",
    properties_sold: 112,
    image_url: "/professional-nepali-female-real-estate-agent-confi.jpg",
  },
]
